# Generated by Django 3.0.8 on 2020-07-12 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a question category (e.g. Math, Programming)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the question', max_length=255)),
                ('question', models.TextField(help_text='Enter Question here', max_length=600)),
                ('answer', models.CharField(help_text='Enter the answer that returns the correct result i.e a number ', max_length=500)),
                ('category', models.ManyToManyField(help_text='Select a category for this question', to='questions.Category')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_at', models.DateField(blank=True, null=True)),
                ('attempt', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, choices=[('p', 'Pass'), ('f', 'Fail'), ('n', 'No attempt')], default='n', help_text='Attempt Status', max_length=1)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.Question')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingQuestionInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_at', models.DateField(blank=True, null=True)),
                ('attempt', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, choices=[('p', 'Pass'), ('f', 'Fail'), ('n', 'No attempt')], default='n', help_text='Attempt Status', max_length=1)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.Question')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the question', max_length=255)),
                ('question', models.TextField(help_text='Enter Question here', max_length=600)),
                ('answer', models.CharField(help_text='Enter the python program that returns the correct result ', max_length=500)),
                ('category', models.ManyToManyField(help_text='Select a category for this question', to='questions.Category')),
            ],
        ),
    ]
