# Generated by Django 3.0.8 on 2020-07-13 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questioninstance',
            name='attempted_at',
        ),
    ]
